### ISSUE TITLE
Improve portability by using musl-fts and removing unnecessary #includes

### ISSUE THREAD

**Issue by absolutelynothinghere** [arp242/bsdgrep#1]
bsdgrep depends on libfts which is specific to GNU libc, however it can be replaced by [musl-fts](https://github.com/void-linux/musl-fts) (BSD-3-Clause) to increase portability. To use musl-fts:

* Copy fts.h and fts.c to this repo and add fts.o to the list of objects
* Change `<fts.h>` to `"fts.h"` in fts.c and util.c
* Remove `#include "config.h"` from fts.c

There are other fixes to get bsdgrep to compile without GNU libc:

* Replace `strcasestr` with `strcasecmp` in util.c (this change was recommended by the compiler, bsdgrep did not compile otherwise)
* Replace `REG_STARTEND` with `(1>>2)` in grep.c
* Remove includes of `<sys/cdefs.h>` `<sys/queue.h>` in file.c grep.c queue.c util.c
* Remove includes of `<bzlib.h>` `<zlib.h>` in grep.h

**Comment by arp242** [comment]
I'll merge a PR for this I guess, but note that this is mostly just a thing I did in an evening three years ago, and I've never really looked at it again, FYI. If you really want to use it then you may be better off maintaining a fork or something.
